### ISSUE TITLE
Be sure to protect against common XML vulnerabilities

### ISSUE THREAD

**Issue by jcopenha** [tableau/tabcmd#15]
https://github.com/tableau/tabcmd2/blob/bed00ff3a6e4dedf8cf66ec8c0edff569c29be92/pythontabcmd2/tableauserverclient/server/request_factory.py#L2

Based on my reading of https://docs.python.org/3/library/xml.html#xml-vulnerabilities i'd investigate the usage of https://pypi.org/project/defusedxml/ to ensure we are protected from all XML vulnerabilities.

**Comment by jacalata** [comment]
This should be implemented within tsc, since we don't do any xml handling directly in tabcmd. 
https://github.com/tableau/server-client-python/issues/988
