### ISSUE TITLE
exe file Permissions when running

### ISSUE THREAD

**Issue by mattlc1989** [tableau/tabcmd#157]
apologies if I am doing this wrong but when I try to login using the updated exe file I get a permission error.

I have replaced the original  exe file from tabcmd with the new one from here

this is the error script

PermissionError at line 15 of C:\Users\MOCALL~1\AppData\Local\Temp\2\_MEI243722\tabcmd.py: [Errno 13] Permission denied: 'C:\\Program Files\\Tableau\\Tableau Server\\2021.4\\extras\\Command Line Utility\\tabcmd.log'

**Comment by mattlc1989** [comment]
I have tried the pip method also ran the pip install fine but them where will the tabcmd.py file be just get 401001: Signin Error
		Error signing in to Tableau Server
any way I try this

obviously I'm missing something , I am using server 2021.4

**Comment by jacalata** [comment]
The new exe doesn't need to be in the same place as the old one: if you just put it on the Desktop or somewhere you normally work, does that fix it? 
Could you try adding --logging-level=debug to the command when you login, and copy the output here?

**Comment by mattlc1989** [comment]
yes i have tried just running in a folder this is what i get

C:\Users\mocallaghan\Downloads>tabcmd login -s https://prod-uk-a.online.tableau.com -u ########-p ########-logging-level=debug
INFO:  Creating new session
INFO:  =====   Server: https://prod-uk-a.online.tableau.com
INFO:  =====   Username: m.lannoncallaghan@fitnessfirst.co.uk
INFO:  Tableau Server Site:
INFO:  Connecting to the server...
INFO:

        401001: Signin Error
                Error signing in to Tableau Server

**Comment by jacalata** [comment]
Hi, sorry for the wait! I just realised that you have not listed a site in the last comment, which is why your login failed. Do you know the name of your site?

**Comment by mattlc1989** [comment]
> Hi, sorry for the wait! I just realised that you have not listed a site in the last comment, which is why your login failed. Do you know the name of your site?

apologies I never usually name my site in the connection just the server 

added my site and can log in now thanks.

running a simple get command  asked my for a password which  cannot then enter ?

![image](https://user-images.githubusercontent.com/110670375/187383431-e17fbed2-24ae-490d-8032-45ba1a64e4fb.png)

**Comment by mattlc1989** [comment]
once I renter my password which i cannot do as i run these on scripts then i get this 

![image](https://user-images.githubusercontent.com/110670375/187436190-d087654d-0585-4021-aded-0865731a3640.png)

**Comment by mattlc1989** [comment]
any help on this ? cannot run any code as constantly  asking for my password ?

![image](https://user-images.githubusercontent.com/110670375/189329979-77e1f58e-f036-4294-bdbd-dccbc0144f66.png)

**Comment by jacalata** [comment]
I'm sorry I didn't help more - I don't really have any idea what's causing this. If you are still having trouble, I would try saving your password in a file and using the argument --password-file <the-file-name> when you log in.

**Comment by jacalata** [comment]
closing as stale.
