### ISSUE TITLE
Exporting Pdf's using parameters and filters not working

### ISSUE THREAD

**Issue by tedkriwiel** [tableau/tabcmd#163]
I've been using bash scripts for the last few years that cycle through a list of strings to filter the view and outputs the dashboards into a series of pdf's. In the last few months those have been failing. I've tried everything I can think of to troubleshoot and still can't get them to work. Here's an example of the command that I run:

`tabcmd export "E-CommunityOverview/E-CommunityProfile?Fund%20Name=Humboldt_Allen%20County" --fullpdf -f "/Volumes/{filepath}/{filename}.pdf" -p $key`
`tabcmd export "E-CommunityOverview/E-CommunityProfile?FundNameFilter=Altamont" --fullpdf -f "/{filepath}/{filename}.pdf" -p $key
`
**Setup:**
- Apple M1 Pro
- macOS Monterey Version 12.5
- Tableau Online

**Results:**
- I am not getting any errors
- The pdf is created and sent to the file path with no issue
- The command ignores the filter parameters in the tableau online url. (Every pdf result is the same unfiltered result.)

**Troubleshooting Steps:**
- The workbook originally filtered on a parameter but I've also tried to filter with a dimension field and neither work
- I've tried formatting the parameter in the url by double encoding it ie: Fund%%20Name=Humboldt_Allen%%20County
- I've tried formatting the command request by adding "Parameters" to the prefix ie: "E-CommunityOverview/E-CommunityProfile?**Paramters.FundNameFilter**=Altamont"  
- I've tried deleting the parameter from the workbook and creating a new one
- I've tried deleting the workbook from Tableau Online and re-publishing
- I've confirmed that the filters work in the Tableau Online UI
- I've confirmed that the filters work when you append the parameters to the URL in Tableau Online

**Comment by jacalata** [comment]
Have you been using the same version of tabcmd the whole time? Can you run tabcmd -v/tabcmd version and share the result?

**Comment by tedkriwiel** [comment]
It's possible that there has been a version change in this process. Here was the result:
tabcmd -v
tabcmd.exe - Tableau Server Command Line Utility v2.0.5

**Comment by jacalata** [comment]
This should be fixed when I check in this change - https://github.com/tableau/tabcmd/pull/164

**Comment by difemaro** [comment]
@jacalata 

Hi, it seems it is not working.  I downloaded and upgraded the tabcmd package, but the filtering is not working.

I have tried with:
tabcmd export -t Entrenamiento "Exportar/Extranjeros?Pais=Ecuador" --fullpdf -f "Ecuador.pdf"

And also with:
tabcmd export -t Entrenamiento "Exportar/Extranjeros" --fullpdf -f "Ecuador.pdf" --filter Pais:Ecuador

I have also tested Tableau Online, Tableau Server.

Regards,

Diego Martinez
Tableau Visionary

**Comment by septatrix** [comment]
Yes it seems like the `export` command is still very much broken. The merge request simply logs it but then does not use the value anymore. This is similar to some other flags which are shown by the CLI to be implemented but simply discarded afterwards (see #169).

**Comment by jacalata** [comment]
This basic issue of filters not applying is fixed in the latest release (2.0.7) - I'll close this now, but feel free to re-open it if there's anything missing or further work needed. Filters with spaces still don't work and that is being tracked separately.
