### ISSUE TITLE
Error while exporting to csv (empty file produced)

### ISSUE THREAD

**Issue by mosuarez1971** [tableau/tabcmd#167]
Hello, when exporting a view to csv, I am getting this INFO message and the output file is empty. It does generate some content if I export to PDF, but I need the CSV version of the view. Were you aware of the issue?

INFO: a bytes-like object is required, not 'generator'

Here is the command used:

tabcmd export "workbook_name/view_name" --csv -f "filename"

Thanks.

Additional details with the DEBUG option:

DEBUG: ExportCommand: 22: Requesting ''workbook/view'' from the server...
DEBUG: ExportCommand: 147: Found attachment: c:<filepath>.csv
DEBUG: ExportCommand: 45: Error saving to file
DEBUG: ExportCommand: 53: a bytes-like object is required, not 'generator'

**Comment by jacalata** [comment]
This is fixed in the development branch and will be in the next release.

**Comment by jacalata** [comment]
This is fixed in the latest release - I'll close this now, but feel free to re-open it if there's anything missing or further work needed.
