### ISSUE TITLE
`export`: `--pagelayout` and `--pagesize` options have no effect

### ISSUE THREAD

**Issue by septatrix** [tableau/tabcmd#169]
The options are present in the argument parser but are not used afterwards. It seems like they should be passed to `
PDFRequestOptions`

**Comment by septatrix** [comment]
The same also seems to be the case for width and height (which I guess correspond to viz-height and viz-width of the [Query View PDF Rest call](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooks_and_views.htm#query_view_pdf). Also is there any functionality similar to the autoscale which we get from the Web UI?

**Comment by septatrix** [comment]
This might be a great candidate for the new REST API available under `/api/-` which states to use the same underlying code as the Web UI. The PDF export in the Web UI seems to be a lot better with proper scaling etc. though it would need an option to specify changed filter values.

**Comment by jacalata** [comment]
This is fixed in the latest release - I'll close this now, but feel free to re-open it if there's anything missing or further work needed.

**Comment by jacalata** [comment]
(That said, width and height are still not fully implemented. I will open a separate bug to track that)
