### ISSUE TITLE
Error in packaging, tabcmd is installed as src

### ISSUE THREAD

**Issue by septatrix** [tableau/tabcmd#170]
When installing tabcmd it is installed under `lib/python3.10/site-packages/src/` instead of `.../tabcmd`.
This can be confusing and even dangerous if other packages make the same mistake and some name clashing happens.

**Comment by septatrix** [comment]
This seems to have been solved with v2.0.6. Could we maybe get a release for that on PyPI?

**Comment by bcantoni** [comment]
Good point - this was fixed in #150 and should be included in the next PyPI release.
