### ISSUE TITLE
Will 2.0.6 or later version support custom views in get/export commands

### ISSUE THREAD

**Issue by weeejw** [tableau/tabcmd#183]

**Comment by jacalata** [comment]
It won't be in 2.0.6 and I don't have a timeline yet, but it is in the roadmap. 
If you can give any specific use cases, I can take that back to a PM to help push it along in priority :)

**Comment by jacalata** [comment]
I'm going to close this as support for custom views is already tracked in our existing feature item https://github.com/tableau/tabcmd/issues/87
As the tag suggests, it does require some server-side updates, so it isn't coming immediately.

**Comment by weeejw** [comment]
understood, thank you! Thanks,JosephOn Nov 10, 2022, at 17:03, Jac ***@***.***> wrote:﻿
I'm going to close this as support for custom views is already tracked in our existing feature item #87
As the tag suggests, it does require some server-side updates, so it isn't coming immediately.
