### ISSUE TITLE
Release Page Issue

### ISSUE THREAD

**Issue by RobertFoltzDBRS** [tableau/tabcmd#188]
Hi,

We are currently testing out the TabCmd 2.0 version to replace the Tableau desktop exe from running the extract refreshes in Tableau Online since MFA has come into effect. We noticed that when downloading the tabcmd-windows.exe from the [2.0.6 release](https://github.com/tableau/tabcmd/releases/tag/v2.0.6) that we are in fact downloading a dev build. I don't think this was intentional.

![image](https://user-images.githubusercontent.com/71773919/195365335-8059ec40-5d35-48eb-bdfe-609274b9f22a.png)

**Comment by jacalata** [comment]
Thanks for pointing it out - this was not intentional and the 2.0.7 release has been checked and now says "v2.0.7" properly. We have some work to do on the automated releases!
