### ISSUE TITLE
Refreshextracts returns 403 but working

### ISSUE THREAD

**Issue by RobertFoltzDBRS** [tableau/tabcmd#189]
Hi,

As part of the testing of the TabCmd 2.0 we noticed that there is an issue when content owners have a creator license when using the refreshextract parameter they get a 403 returned to them, even though they are the owner of said data source they are requesting to refresh. If the user is a Site Administrator they do not encounter this issue.

Interestingly enough it is actually working but form some reason there is an error getting returned making it look like it's not working. In the screenshot below you can see that I executed the command and receive a 403 but when I immediately do the same command again I get a different response saying it's already queued. I can also confirm on the jobs tab of Tableau Online that the job was kicked off to refresh the data source.

![403_error](https://user-images.githubusercontent.com/71773919/195381814-cf5d30fe-430d-4e44-89e0-5fc90bbe1fdf.png)

**Comment by jacalata** [comment]
That's very odd - I have noticed the error, but never actually checked to realize that it was scheduling the job anyway. That might make it easier to fix. Thanks!

**Comment by jacalata** [comment]
I got someone else to look into this and they couldn't repro it - now I can't either, although I'm sure I saw it in the past. Is this still happening for you, @RobertFoltzDBRS ?

**Comment by RobertFoltzDBRS** [comment]
Hi @jacalata and @fholt

I haven't tested the latest releases, and I personally have just been using the API. I'll see if using version 2.0.10 of tabcmd works.

Thanks,
Robert

**Comment by dkwon-salesforce** [comment]
Hi @RobertFoltzDBRS @fholt,

It would help greatly if you could share the following information for your error:

- Tableau Cloud server name
- Tableau Cloud site name
- User name
- Timestamp

@RobertFoltzDBRS we have most of the information from your screenshot, please include the timestamp as well.

Thank you,
Don

**Comment by fholt** [comment]
"c:\tabcmd\tabcmd" refreshextracts --server "https://us-east-1.online.tableau.com<https://us-east-1.online.tableau.com/>" --site "skylarcapital" --token-name "FosterPAT" --token-value "<token-value>" --project "Default" --datasource "wx_Latest_Daily (EuropeDB)"

User name is ***@***.******@***.***>

Not sure what you mean by Timestamp.

**Comment by jacalata** [comment]
This has been fixed internally, I believe will be in the 23.2.0 release.
