### ISSUE TITLE
--pagesize unspecified doesn't work for tabcmd export

### ISSUE THREAD

**Issue by lhanik** [tableau/tabcmd#192]
Using `--pagesize unspecified` ends with:
```
 400000: Bad Request
                Payload is either malformed or incomplete
```

![image](https://user-images.githubusercontent.com/116584219/197578562-0765ae9f-9e41-421c-96a5-14c8f64627e9.png)

**Comment by jacalata** [comment]
ok - finally got round to this one, and I can't reproduce it. Do you still see this error? If so, can you give me your version output?

**Comment by lhanik** [comment]
> ok - finally got round to this one, and I can't reproduce it. Do you still see this error? If so, can you give me your version output?

@jacalata:
![image](https://user-images.githubusercontent.com/116584219/205057139-a4e3fa85-f1ea-4215-935d-8e5c02e81124.png)

**Comment by jacalata** [comment]
I still haven't seen it. Here's my command: 
tabcmd export Regional/Obesity --pdf -f unspec.pdf --pagelayout portrait --pagesize unspecified -l debug

can you re-run with the logging enabled, "--logging-level debug"?

**Comment by lhanik** [comment]
Hi @jacalata, please find output below:
![image](https://user-images.githubusercontent.com/116584219/207004583-711a3bf8-3b20-4ee8-bdcb-96164b22896d.png)

**Comment by lhanik** [comment]
@jacalata - was proper version published on https://github.com/tableau/tabcmd/releases/tag/v2.0.11? It looks like a dev version again:
![image](https://user-images.githubusercontent.com/116584219/223078987-90ad6d15-ce27-4657-ac69-c06a6c578b05.png)

**Comment by jacalata** [comment]
ah, looks like I didn't set the version for building the exe. I believe it is the correct release, but I'll get that fixed in the next one.
