### ISSUE TITLE
'Session' object has no attribute 'logger'

### ISSUE THREAD

**Issue by fholt** [tableau/tabcmd#221]
tabcmd has been working for months, then last night we starting getting errors.  See attached tabcmd.log.  I tried downloading the latest...same error.

Here is the command I am using...
"c:\tabcmd\tabcmd" refreshextracts --server "https://us-east-1.online.tableau.com" --site "skylarcapital" --token-name "FosterPAT" --token-value "<token-value>" --project "Default" --datasource "wx_Latest_Daily (EuropeDB)"

I have a number datasources that I update using tabcmd.

Please advise.

[tabcmd.log](https://github.com/tableau/tabcmd/files/10450203/tabcmd.log)

**Comment by jacalata** [comment]
Try running "tabcmd logout" and then try your command again. Does that work?

**Comment by fholt** [comment]
Just doing tabcmd logout doesn't work...

C:\Tableau Automation>"c:\tabcmd\tabcmd" logout
logging: INFO
'Session' object has no attribute 'logger'
Traceback (most recent call last):
  File "tabcmd\commands\auth\session.py", line 360, in _read_from_json
KeyError: 'tableau_auth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tabcmd\execution\tabcmd_controller.py", line 47, in run
  File "tabcmd\commands\auth\logout_command.py", line 24, in run_command
  File "tabcmd\commands\auth\session.py", line 51, in __init__
  File "tabcmd\commands\auth\session.py", line 378, in _read_from_json
AttributeError: 'Session' object has no attribute 'logger'

**Comment by jacalata** [comment]
@fholt this should have been fixed in the 2.0.11 release, which added a way to recover if the saved file is unreadable. Did you solve the problem yourself, or does 2.0.11 work for you?
