### ISSUE TITLE
Delete Group Command

### ISSUE THREAD

**Issue by ovinis** [tableau/tabcmd#24]
Docs for Tabcmd - https://help.tableau.com/current/server/en-us/tabcmd_cmd.htm#id0d009916-bee3-4ef0-a6ac-22188c0e7f30

Tabcmd2 "delete group" command contains flag --name as group name. To delete a group Tabcmd2 uses `tabcmd2 deletegroup --name "ExampleGroup"`. Original Tabcmd does not use --name flag. Update the command code accordingly.

**Comment by jacalata** [comment]
see also #26 and #31
