### ISSUE TITLE
--Width Argument not Working

### ISSUE THREAD

**Issue by pmhollow6** [tableau/tabcmd#240]
This command in the 2/21/2023 version of Tabcmd 2.0 produces a PDF that does not size the columns correctly in the WTD.pdf file even though it is set to width 1600:

tabcmd export "/MarketingYield-MinivacEfficiencies/WTD?:refresh=yes" --filter "Report Date=3/12/2023" --pdf --pagesize unspecified --pagelayout landscape --width 1600

Tabcmd 2.0 file: [WTD.pdf](https://github.com/tableau/tabcmd/files/10962280/WTD.pdf)

Example of report created with old Tabcmd with correct sizing:
[WTD.pdf](https://github.com/tableau/tabcmd/files/10962396/WTD.pdf)

**Comment by jacalata** [comment]
Yes, I'm afraid that the width/height parameters are still waiting on a server-side fix to work in tabcmd 2. It's tracked in https://github.com/tableau/tabcmd/issues/94 but the name isn't very clear.

**Comment by jacalata** [comment]
updated the title of the other one, closing this
