### ISSUE TITLE
"createsiteusers" with a CSV file returns the error "line X for user ''Invalid value for 3: Explorer'': '''' Too many errors encountered in CSV file."

### ISSUE THREAD

**Issue by pcmcsf** [tableau/tabcmd#251]
Following the "createsiteusers" command documentation [here](https://tableau.github.io/tabcmd/docs/tabcmd_cmd.html#createsiteusers-filenamecsv) and the CSV Import File Guidelines [here](https://help.tableau.com/current/online/en-us/csvguidelines.htm), I attempted to create a new user using a CSV file with the following entry:

_email address_,,,Explorer,None,true

Running the command `tabcmd createsiteusers "path to CSV file"` resulted in the error:

line _email address_ for user ''Invalid value for 3: Explorer'': ''''
Too many errors encountered in CSV file
None
Exiting...

This was reproduced in v2.0.11 of tabcmd 2.0

**Comment by rymatt830** [comment]
This issue is affecting us, too. We've been unable to automate user creation in our Cloud environment with TABCMD 2.0 for three-four weeks now. This is causing a lot of confusion for our users who expect to have access but do not because of this bug. Is there any ETA? Thank you.

**Comment by JeremyCalloud** [comment]
I am affected by the same issue. I have found out after trying a bunch of things that you need to submit the arguments in lower case.

"Explorer" will be returned as invalid value, but "explorer" will work. Same with "None" and "none". I ended up using 1 instead of TRUE as well.

The script will now process every line but will also skip them all, returning a "Payload is either malformed or incomplete" error message, so we are still unable to create users.

**Comment by rymatt830** [comment]
Any updates?

**Comment by rymatt830** [comment]
I am running into this error again. Like last time, following the "createsiteusers" command documentation [here ](https://tableau.github.io/tabcmd/docs/tabcmd_cmd.html#createsiteusers-filenamecsv) and the CSV Import File Guidelines [here](https://help.tableau.com/current/online/en-us/csvguidelines.htm), I attempted to create a new user using a CSV file with the following entry:

user1@domain.com,,,Viewer,None,true

This failed and the following was captured in the logs:

line user1@domain.com for user ''Invalid value for 3: Viewer'': ''''
