### ISSUE TITLE
tabcmd stopped working yesterday

### ISSUE THREAD

**Issue by fholt** [tableau/tabcmd#253]
I've been using tabcmd for a long time.  It started failing yesterday afternoon (see command and log information below).  I downloaded the latest tabcmd but it still fails.

Please advise.
Thanks,
Foster

C:\Tableau Automation>**"c:\tabcmd\tabcmd" refreshextracts --server "https://us-east-1.online.tableau.com" --site "skylarcapital" --token-name "FosterPAT" --token-value "******" --project "default" --datasource "vwPowerTimeSpread (ExternalData.ICE)"**
Creating new session
=====   Server: https://us-east-1.online.tableau.com
=====   Token Name: FosterPAT
Tableau Server Site: skylarcapital
Connecting to the server...
HTTPSConnectionPool(host='us-east-1.online.tableau.com', port=443): Max retries exceeded with url: /auth?format=xml (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)'))))
Exiting...

**Comment by bcantoni** [comment]
@fholt around that same time there was a short degradation for some Tableau Cloud users (related to sign-in): https://trust.tableau.com/incidents/xyxjyn81c4fs

I'm not sure if these two things are related, but the incident I mentioned has been resolved now. Can you confirm whether you're still seeing the problem you reported?

**Comment by fholt** [comment]
Possibly.  It has started working again.  Tableau support thought it was our issue (proxy issue).  However, nothing on our end changed but now all is working again.

Thank you for your quick response.

**Comment by bcantoni** [comment]
Okay thanks for confirming! Let's assume this was related to that outage and we'll close it out.
