### ISSUE TITLE
Document new filtering syntax

### ISSUE THREAD

**Issue by jacalata** [tableau/tabcmd#254]
Released in 2.0.11

Existing syntax: (can be used in classic tabcmd and Tabcmd 2)
_tabcmd export /WorldIndicators/Population?Birth%20Rate%20Bin=1.5-3%25 --pdf_

New syntax, with no need to encode the parameter values:
_tabcmd export /WorldIndicators/Population --pdf -f b1.pdf --filter "Birth Rate Bin=1.5-3%"_

Question for documenting: can an ampersand be entered in this option without encoding?

**Comment by kanishk496** [comment]
I would also like to understand this. I have tried the following commands to filter based on a value containing "&" but didnt work for me. 
```
tabcmd export "/Action/Dashboard1" --pdf -f "Dashboard1.pdf" --filter "Account Name1=Mahindra & Mahindra"
tabcmd export "/Action/Dashboard1" --pdf -f "Dashboard1.pdf" --filter "Account Name1=Mahindra %26 Mahindra"
tabcmd export "/Action/Dashboard1" --pdf -f "Dashboard1.pdf" --filter "Account Name1=Mahindra %%26 Mahindra"
```

The error I get is: "list index out of range"

What would be the right command to pass "&" in this case?
