### ISSUE TITLE
Filtering does not work for a full workbook to download --fullpdf 

### ISSUE THREAD

**Issue by maddinenisandeep** [tableau/tabcmd#257]
We are having issues using tabcmd 2.0 to export PDF files. We have a filter setup to show a list of users, and we either show all details, or a specific user

**Comment by jacalata** [comment]
Yes, filtering an entire workbook is not currently possible in the new tabcmd. If you specifically need this feature, you will need to continue using classic tabcmd for now. 

This is being tracked at https://github.com/tableau/tabcmd/issues/233
