### ISSUE TITLE
tabcmd V2.0.12 not display thai language

### ISSUE THREAD

**Issue by NUTCHIJ** [tableau/tabcmd#265]
I use tabcmd get .png then not display thai language (show english only)
please suggest me for solve it 

![Capture](https://github.com/tableau/tabcmd/assets/149059557/16d8bcac-58bf-4e8e-8883-a0b31be5cfed)

**Comment by jacalata** [comment]
This was identified as an issue on the server, and fixed late 2023 so I will close this issue. Please re-open this bug if you are still seeing any problems!
