### ISSUE TITLE
Syntax not recognized in Jupyter Notebooks

### ISSUE THREAD

**Issue by aasper-msh** [tableau/tabcmd#269]
Hello! I can run tabcmd from Command Prompt, but when I try to run it from a Jupyter Notebook, I get an "invalid syntax" error. Is tabcmd incompatible with Jupyter Notebooks? Or is there a different syntax I should be using? Thanks!

**Comment by jacalata** [comment]
Tabcmd is a command line executable. It does not use python syntax to run. You need to look up how to invoke an executable from jupyter notebooks.

**Comment by jacalata** [comment]
(If you just want to write python code, perhaps you would find it easier to use the tableau server client that tabcmd is built on - https://github.com/tableau/server-client-python)

**Comment by aasper-msh** [comment]
It worked to just add an exclamation point in front of tabcmd.

**Comment by jacalata** [comment]
Yep, sounds right https://opensarlab-docs.asf.alaska.edu/user-guides/jupyter_magic/#:~:text=In%20IPython%20syntax%2C%20the%20exclamation,the%20command%20in%20the%20shell.
