### ISSUE TITLE
Unrecognized option: --token-name

### ISSUE THREAD

**Issue by lenzyh** [tableau/tabcmd#275]
Hi I am facing issues to login using tabcmd when using PATs as login credentials. The reason I want to use PATs is that my org previously implemented MFA
ps: tabcmd version : 2.0.12

**Comment by jacalata** [comment]
Could you tell me how you are running the program? e.g did you download an executable from the releases page? What is the exact command line you are using?

**Comment by kamil234** [comment]
My guess you have one of the versions of tabcmd which has a different command switch. 
Run tabcmd login -h and look at the commands in the help page. 
In one of the versions it was switched from -tn to --token-name. If you use --token-name and the command expect -tn it will error out.
