### ISSUE TITLE
login with token throws "no attribute prompt"

### ISSUE THREAD

**Issue by jonathan-dufault-kr** [tableau/tabcmd#51]
'Traceback (most recent call last):
  File "C:\Users\jd59203\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jd59203\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jd59203\Anaconda3\Scripts\tabcmd.exe\__main__.py", line 7, in <module>
  File "C:\Users\jd59203\Anaconda3\lib\site-packages\tabcmd\tabcmd.py", line 16, in main
    command_context.execute_command()
  File "C:\Users\jd59203\Anaconda3\lib\site-packages\tabcmd\context.py", line 39, in execute_command
    command_strategy = command_strategy_type.parse()
  File "C:\Users\jd59203\Anaconda3\lib\site-packages\tabcmd\commands\auth\login_command.py", line 18, in parse
    args = LoginParser.login_parser()
  File "C:\Users\jd59203\Anaconda3\lib\site-packages\tabcmd\parsers\login_parser.py", line 25, in login_parser
    if args.prompt and args.username:
AttributeError: 'Namespace' object has no attribute 'prompt'`

commenting out the references to args.prompt fixes the error, but I'm certain I'm bypassing some critical logic

`        if False: #args.prompt and args.username:
            args.password = getpass.getpass("Password:")
        if False: # args.prompt and args.token_name:
            args.token = getpass.getpass("Token:")
        if args.no_prompt and args.username and args.password is None:
            logger.error("Please provide password")
            sys.exit()
        if args.no_prompt and args.token_name and args.token is None:
            logger.error("Please provide token")
            sys.exit()
        if args.username and args.password is None:
            args.password = getpass.getpass("Password:")
        if args.token_name and args.token is None:
            args.token = getpass.getpass("Token:")
        if args.site is None or args.site == "Default":
            args.site = ''
        return args
`

**Comment by jacalata** [comment]
I think this'll be fixed by one of my in-progress branches

**Comment by jonathan-dufault-kr** [comment]
oh nice. is there any way to help on this project? this tool seems pretty neat

**Comment by jacalata** [comment]
Glad you like it! We definitely plan to accept pull requests. Right now we are working pretty hard to get it to parity with the original client for release, so if you would like to add something then it would probably be most efficient to spot some functionality that is missing from the original client, to avoid us accidentally repeating each other's work. https://help.tableau.com/current/server/en-us/tabcmd_cmd.htm.

**Comment by jacalata** [comment]
This is now actually fixed - look forward to any more feedback now you can use it!
