### ISSUE TITLE
Namespace' object has no attribute 'prompt

### ISSUE THREAD

**Issue by hani1814** [tableau/tabcmd#53]
Hi,

the latest version is throwing this error when trying to login

 File "e:\python37\lib\site-packages\tabcmd\parsers\login_parser.py", line 25, in login_parser
    if args.prompt and args.username:
AttributeError: 'Namespace' object has no attribute 'prompt'

**Comment by jacalata** [comment]
yep - this fix is in progress, thanks!

**Comment by jacalata** [comment]
This is now actually fixed - look forward to any more feedback now you can use it!
