### ISSUE TITLE
Remove Mention of PyInstaller?

### ISSUE THREAD

**Issue by WillAyd** [tableau/tabcmd#64]
Just curious if there's any consideration to not using PyInstaller at all, whether documented or for end users. Unless I am mistaken this is a pure python project. It might be an easier experience for end users to just have them install via pip or conda?

**Comment by jacalata** [comment]
It is pure python, but the tool it replaces is not, and we want to match the [existing install experience](https://help.tableau.com/current/server/en-us/tabcmd.htm) by having an exe/etc downloadable from the support pages . (Many of the intended users for tabcmd are not really technical)

**Comment by WillAyd** [comment]
Makes sense - thanks for the response
