### ISSUE TITLE
Use pyproject.toml

### ISSUE THREAD

**Issue by WillAyd** [tableau/tabcmd#72]
Per PEP 518 this would be a more future proof option than using a setup.cfg file. 

Similarly you can add entries for black like `line-length = 120` instead of specifying as a command line argument

**Comment by jacalata** [comment]
yes - I was expecting to need this as part of replacing the `setup.py test` workflow, but it didn't come up. This would be great.

**Comment by jacalata** [comment]
completed these upgrades in https://github.com/tableau/tabcmd/commit/038c9d7fe4231c7e494287c2019931724ec29a2f
